eureka:
  client:
    service-url:
      defaultZone: http://eureka-7001:7001/eureka #注册中心的地址，注意最后有一个/eureka
spring:
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  messages:
    basename: i18n.msg,i18n.validate
  jackson:
    date-format: yyyy-MM-dd HH:mm
    time-zone: Asia/Shanghai
  application:
    name: cloud-user-service123
  zipkin:
    base-url: http://localhost:9411/  # 链路追踪的服务器地址
  sleuth:
    sampler:
      probability: 1  #(范围是0-1) 指的是收集数据的比例  采集数据的比例（0-1）
mybatis:
  mapper-locations: classpath*:mybatis/mapper/**/*.xml    #
  configuration:
    map-underscore-to-camel-case: true  #
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #


---
spring:
  profiles: pro
  datasource:
    url: jdbc:mysql://120.25.223.121/tcmm_db?serverTimezone=Asia/Shanghai

---
server:
  port: 8002
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://120.25.223.121/tcmm_db_test?serverTimezone=Asia/Shanghai
logging:
  level:
    com.qianfeng.cqjava.dao: debug
---
server:
  port: 8003
spring:
  profiles: dev2
  datasource:
    url: jdbc:mysql://120.25.223.121/tcmm_db_test?serverTimezone=Asia/Shanghai
logging:
  level:
    com.qianfeng.cqjava.dao: debug
